package com.example.accessingdatamysql;

import com.example.accessingdatamysql.first.Tbhistory;
import com.example.accessingdatamysql.first.TbhistoryRepository;
import com.example.accessingdatamysql.second.DAT_HouseHoldData;
import com.example.accessingdatamysql.second.DAT_HouseHoldDataRepository;
import com.example.accessingdatamysql.service.MainService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import java.text.SimpleDateFormat;
import java.util.*;

/**
 * @author caiwl
 * @date 2020/4/3 8:52
 */
@Controller // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class MainController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private TbhistoryRepository tbhistoryRepository;
    @Autowired
    private DAT_HouseHoldDataRepository dat_houseHoldDataRepository;
    @Autowired
    private MainService mainService;

    @GetMapping(path="/add") // Map ONLY POST Requests
    public @ResponseBody
    String addNewUser (@RequestParam String name, @RequestParam Double tem) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        Tbhistory n = new Tbhistory();

        n.setDeviceName(name);
        n.setTem(tem);
        n.setRecordTime(new Date());
        tbhistoryRepository.save(n);
        return "Saved";
    }
    @GetMapping("/rkmonitor/getList")
    public @ResponseBody Object getList(){
        return  tbhistoryRepository.findAll();
    }
    @GetMapping("/UserDatabase/getList")
    public @ResponseBody Object getListU(){
        return  dat_houseHoldDataRepository.findAll();
    }
    @GetMapping("/first")
    public @ResponseBody List<DAT_HouseHoldData> first(){
            try{
                Date date=new   Date();//取时间
                System.out.println(date.toString());
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                String fom1=sdf.format(date);
                date=sdf.parse(fom1);
                List<Tbhistory> list=  tbhistoryRepository.findAllByRecordTimeBefore(date);
                List<DAT_HouseHoldData> datas=this.mainService.transfer(list);
                return datas;
            }catch (Exception e){
                System.out.println(e);
                return null;
            }

    }

    @GetMapping("/timing")
    public @ResponseBody List<DAT_HouseHoldData> timing(){
        try{
            Date date=new   Date();//取时间
            System.out.println(date.toString());
            Calendar calendar   =   new GregorianCalendar();
            calendar.setTime(date);
            calendar.add(calendar.DATE,-1);//把日期往后增加一天.整数往后推,负数往前移动
            Date date1=calendar.getTime();   //这个时间就是日期往后推一天的结果
            System.out.println(date1.toString());
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String fom1=sdf.format(date1);
            date1=sdf.parse(fom1);
            List<Tbhistory> list=  tbhistoryRepository.findAllByRecordTimeBetween(date1,date);
            List<DAT_HouseHoldData> datas=this.mainService.transfer(list);
            return datas;
        }catch (Exception e){
            System.out.println(e);
            return null;
        }

    }
    @GetMapping("/hours")
    public @ResponseBody List<DAT_HouseHoldData> hours(){
        try{
            Date date=new   Date();//取时间
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:00:00");
            String fom1=sdf.format(date);
            date=sdf.parse(fom1);
            System.out.println(date.toString());
            Calendar calendar   =   new GregorianCalendar();
            calendar.setTime(date);
            calendar.add(calendar.MINUTE,-61);
            Date date1=calendar.getTime();   //这个时间就是日期往后推一天的结果
            System.out.println(date1.toString());
            String fom2=sdf.format(date1);
            date1=sdf.parse(fom2);
            List<Tbhistory> list=  tbhistoryRepository.findAllByRecordTimeBetween(date1,date);
            List<DAT_HouseHoldData> datas=this.mainService.transfer(list);
            return datas;
        }catch (Exception e){
            System.out.println(e);
            return null;
        }

    }
}
